### ISSUE TITLE
It'd be awesome if we could give the spandrel a facelift with some new functionality. :)

### ISSUE THREAD

**Issue by zelenooki87** [chaiNNer-org/spandrel#152]
following architectures:

**FFTFormer:**
https://github.com/kkkls/fftformer
**M3SNet:**
https://github.com/Tombs98/M3SNet
**MHNet:**
https://github.com/Tombs98/MHNet
**Maxim:**
https://github.com/vztu/maxim-pytorch/tree/main
And:
**Restormer:**
https://github.com/swz30/restormer
(because, KBNet and Nafnet do not work properly for some images - I opened a bug issue about this)

**Comment by RunDevelopment** [comment]
I added support for Restormer (#170), FFTFormer (#171), and M3SNet (#172). The other 2 are weird:

- The official Maxim implementation uses a different framework that isn't compatible with PyTorch. You linked a PyTorch re-implementation of Maxim.
- MHNet is a mess. The author *deleted* the arch code (it's still accessible via git history) and there are no pretrained models. The paper makes it out to be an amazing arch, so I wonder why the repo has these problems. Anyway, I already put together the arch code, but it's useless without pretrained models to test it. Without pretrained models, I cannot add MHNet.

**Comment by zelenooki87** [comment]
Thank you very much, friend! I saw them in benchmark tests on the paperswithcode website, so I thought they would be okay. I haven't tested them all. Thank you very much again!

**Comment by zelenooki87** [comment]
Is it possible to add support for RESTORMER's gaussian_color_denoising_blind.pth model? ( https://drive.google.com/drive/folders/1Qwsjyny54RZWa7zC4Apg7exixLBo4uF0 )
 Chaninner not supports it.
Thank you again.

**Comment by RunDevelopment** [comment]
> Chaninner not supports it.

Because we haven't updated spandrel yet. Chainner currently doesn't support any of the above architectures, but it will in a few days :)

> Other restormer models that I have tested working okay.

How...

**Comment by RunDevelopment** [comment]
I'm going to close this issue now. 

I'm unsure about the PyTorch reimplementation of Maxim. It might be useful, but it feels a little weird to add it. Please make a separate issue if the architecture is dearly wanted.

MHNet is rejected due to problems with the repo (author deleted arch code, no pretrained models). If those problems are somehow resolved in the future, we can add it then.
