### ISSUE TITLE
Any chances to introduce FeMaSR support?

### ISSUE THREAD

**Issue by zelenooki87** [chaiNNer-org/spandrel#17]
Thanks to devs for great project.
I would like to see support for FeMaSR project in chainner:
https://github.com/chaofengc/FeMaSR
Pretty good results with that solution.

Thanks in advance!

**Comment by zelenooki87** [comment]
Thank you devs for implementing FemaSR :)
I have some errors for dimension for scanned or cropped images that are not classic 4:3 shape.
FBCNN and other models dont have these problems.
Keep rocking!
<img width="1280" alt="image" src="https://github.com/chaiNNer-org/spandrel/assets/75204635/1ca414a7-25e9-41c7-9575-3a1e08bbd6b6">

**Comment by RunDevelopment** [comment]
> I have some errors for dimension for scanned or cropped images that are not classic 4:3 shape.

2x FeMaSR models require the width and height of the input image to be multiples of 32. Unfortunately, chainner currently doesn't account for that, and so you'll get this shape error. This is something we'll have to fix (https://github.com/chaiNNer-org/chaiNNer/issues/2335).

In the meantime, you can work around this issue by padding the input image yourself. It's cumbersome, but it can be done.
![image](https://github.com/chaiNNer-org/spandrel/assets/20878432/07984e3e-4008-4d9b-83e5-ff35d67628c7)

**Comment by zelenooki87** [comment]
I tried with this "complicated" way, but unsuccessfull. again errors. Maybe I mistaked somehow.But tried in batch.
<img width="1280" alt="image" src="https://github.com/chaiNNer-org/spandrel/assets/75204635/b0b29640-1657-4364-bec5-6b8c38e98d05">
<img width="1280" alt="image" src="https://github.com/chaiNNer-org/spandrel/assets/75204635/c61a7cc1-0815-4e60-a6ba-40ad469844b4">
input image was 640x480px not 1280x960..as error saying.
Could you please share this method project file (.chn) but modifed for batch processing?
thanks!

**Comment by RunDevelopment** [comment]
Your tile size is set to Auto, so the Upscale node may resize your image internally. Set it to No Tiling and then it should work.
