### ISSUE TITLE
Unsupported models

### ISSUE THREAD

**Issue by vietpho** [chaiNNer-org/spandrel#180]
The README states that the RGT model is supported,
but when I try to use the RGT model with Chainner, I get an error saying it is not supported. 
Could you check and fix this issue?

+ DCTLSA and M3SNet models too.

**Comment by RunDevelopment** [comment]
We only recently added support for these models and haven't released those changes yet. Sorry for the confusion.

We haven't made a release yet, because we are currently making some larger changes to this library as a whole. Finishing those might take us another week or so.
