### ISSUE TITLE
UpCunet2x_Fast support for ShuffleCugan

### ISSUE THREAD

**Issue by NevermindNilas** [chaiNNer-org/spandrel#182]
Hi, I was reading through the code and failed to see any mentions of shufflecugan, are there any plans to support sudo's shufflecugan model based on UpCunet2x_Fast?

https://openmodeldb.info/models/2x-sudo-shuffle-cugan-9-584-969

Amazing work so far guys, much appreciated!

**Comment by RunDevelopment** [comment]
Looks very doable. The architecture itself is very simple and should be easy to detect. 

The only issue is that sudo didn't license the code. So we need to ask them for a license before we can add it.

**Comment by NevermindNilas** [comment]
Awesome, I just asked him to do it.
Thank you!

**Comment by styler00dollar** [comment]
Shuffle Cugan uses `UpCunet2x_fast()` from [bilibili/ailab](https://github.com/bilibili/ailab/blob/2799af78ef105b414cc4b796c67c8511acdcdf6f/Real-CUGAN/VapourSynth/upcunet_v3_vs.py#L632) with pro mode set to false.

**Comment by RunDevelopment** [comment]
Oh, I didn't even notice that when I added Real-CUGAN. Then it's MIT too. Thanks!
