### ISSUE TITLE
DPIR Support.

### ISSUE THREAD

**Issue by NevermindNilas** [chaiNNer-org/spandrel#191]
Hi,

Any plans on supporting DPIR for denoising.

https://github.com/cszn/DPIR

Also, the model(s) link for KBNet is dead.

Thank you!

**Comment by RunDevelopment** [comment]
Sure!

> Also, the model(s) link for KBNet is dead.

Yikes. Thanks for reporting. I made a PR to fix this. In the meantime, here's [the correct link](https://mycuhk-my.sharepoint.com/:f:/g/personal/1155135732_link_cuhk_edu_hk/EofsV3eVcAxNlrW72JXqzRUBhkM1Mzw50pJ3BHlAyMYnVw?e=MeMB5H).

**Comment by NevermindNilas** [comment]
This is beyond the scope of this issue, but any idea when 0.2.3 will be released with the new features and bugfixes?

**Comment by joeyballentine** [comment]
Once we get the release flow working for the new split registry packages, we will release 0.3.0.
