### ISSUE TITLE
About the definition of lk_type in plksr

### ISSUE THREAD

**Issue by umzi2** [chaiNNer-org/spandrel#256]
Hello, I noticed that you decided not to add a definition for lk_type in plksr. In general, I don’t think that anyone will change this parameter, but if they change it, the model will become incompatible. Can its definition and the following parameters be added? [I did it like this:](https://github.com/scanlate-wiki/nusselt/blob/master/src/nusselt/architectures/plksr/__init__.py#L40)

**Comment by joeyballentine** [comment]
Just FYI: your repo is still GPLv3, so me looking at it, legally speaking, means I can now not implement this in spandrel without violating your license since spandrel is now MIT licensed. RunDevelopment now has to implement this instead of me.

**Comment by joeyballentine** [comment]
Btw, don't take that last comment the wrong way. I appreciate you pointing this out for us -- I just wanted to mention it in case you were unaware that we now cannot reference nusselt anymore, becusse I also was not aware of that until I started implenting this
