### ISSUE TITLE
Retinexformer support?

### ISSUE THREAD

**Issue by zelenooki87** [chaiNNer-org/spandrel#269]
https://github.com/caiyuanhao1998/Retinexformer
Really nice project.
Thank you very much in advance!

**Comment by zelenooki87** [comment]
Hey, the FiveVK model does some really beautiful tone and color correction, it's great!
I converted it to an ONNX model from Retinexformer, but I'm running into some errors in Chainner when I try to load it with cropped images that have non-standard dimensions. It seems to work fine on everything else, though.
It would be fantastic if you could incorporate this architecture, especially since it doesn't look like it needs any extra dependencies.
Thanks again for everything!
Best,
Milan

**Comment by joeyballentine** [comment]
Anything is possible, it just matters if we're willing to do the work to add it. It takes time to properly add support for an arch

**Comment by zelenooki87** [comment]
Okay, I will patiently wait and hope then. :)

**Comment by zelenooki87** [comment]
> Anything is possible, it just matters if we're willing to do the work to add it. It takes time to properly add support for an arch

Can I get a contact email? I'm considering a donation for the implementation of Retinexformer. Thank you.
