### ISSUE TITLE
Create pypi source distribution or split repository into two: One for `spandrel` and one for `spandrel-extra-arches`

### ISSUE THREAD

**Issue by alsa64** [chaiNNer-org/spandrel#273]
This would simplify packaging spandrel for various package managers like nix. Since the version number of spandrel and spandrel-extra-arches aren´t the same (0.3.4 and 0.1.1 right now), it would also allow for tracking them in separate tags.

Ideally the `pyproject.toml` file would be in the root of each repository.

**Comment by joeyballentine** [comment]
I don't really see why it's an issue. Just clone the repo, cd into each lib individually and treat it like its own package

**Comment by alsa64** [comment]
At the moment, I use a handwritten package for spandrel, while it works, the automated package generators tend to fail as the pypi version is only available in binary form (see no  [Source Distributions warning](https://pypi.org/project/spandrel/0.3.4/#files)) or because right now this is a monorepo.

In case someone needs it, here's a nix package for the current version of spandrel:
```nix
{
  lib,
  buildPythonPackage,
  fetchFromGitHub,
  python3,
}:
let
  p_version = "0.3.4";
  repo = fetchFromGitHub {
    owner = "chaiNNer-org";
    repo = "spandrel";
    rev = "v${p_version}";
    hash = "sha256-cwY8gFcaHkyYI0y31WK76FKeq0jhYdbArHhh8Q6c3DE=";
  };
in

buildPythonPackage {
  pname = "spandrel";
  version = p_version;
  pyproject = true;

  src = "${repo}/libs/spandrel";

  nativeBuildInputs = with python3.pkgs; [
    setuptools
    wheel
  ];

  propagatedBuildInputs = with python3.pkgs; [
    torch
    torchvision
    safetensors
    numpy
    einops
    typing-extensions
  ];

  pythonImportsCheck = [ "spandrel" ];

  meta = with lib; {
    description = "Spandrel gives your project support for various PyTorch architectures meant for AI Super-Resolution, restoration, and inpainting. Based on the model support implemented in chaiNNer";
    homepage = "https://github.com/chaiNNer-org/spandrel";
    license = licenses.mit;
    maintainers = with maintainers; [ ];
  };
}
```

**Comment by alsa64** [comment]
No problem, certainly not a huge issue, this mostly affects people using nix for development using tools to generate packages from a requirements.nix file, with nix being a niche community, the intersection between nix and spandrel users is probably relatively small.

Out of curiosity, why the monorepo? Is it because the extra arches were historically part of the main package to carry forward old issues?

**Comment by joeyballentine** [comment]
> Out of curiosity, why the monorepo?

Simplicity. They were originally one package, and since they share common code it's a lot easier to be able to make changes to both at once than to have to deal with updating spandrel first then making subsequent changes to the extra arches package. The only reason they were split out was for licensing reasons, so this way keeps it closer to having it as one package while actually publishing it as two.
